[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.1", features = ["sqlx-mysql", "macros", "runtime-tokio-native-tls"] }
tokio = { version = "1.41.1", features = ["full"] }

